#Fill here the Google Maps API keys for your application
development:
ABQIAAAAlnNkiJP9vmPCrrYAO4Ea1BSb6uJFH8ituLuE6RdcmPwyHL5RMxSZzU4kVeEjRoUVZ8dpL38LNUugxw

test:
 ABQIAAAAlnNkiJP9vmPCrrYAO4Ea1BSb6uJFH8ituLuE6RdcmPwyHL5RMxSZzU4kVeEjRoUVZ8dpL38LNUugxw

production:
 flashmobstream.r09.railsrumble.com: ABQIAAAAlnNkiJP9vmPCrrYAO4Ea1BSb6uJFH8ituLuE6RdcmPwyHL5RMxSZzU4kVeEjRoUVZ8dpL38LNUugxw